version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       java: openjdk8
       
    commands:
      - echo "In Install"
      
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - mvn clean package
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
     - '**/*.war'
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
  base-directory: '**/webapp/'
#cache:
  #paths:
    # - paths
